Study
tunkcalb/cote pull request #4
Opened 2022-07-06 17:11 UTC by tunkcalb

2022-07-08 04:05 UTC, misut commented
issue(blocking): 브랜치 컨플릭트 발생해서 머지 안되니까 밑에 Resolve conflicts 버튼 눌러서 확인해봐 ㅇㅇ

2022-07-08 04:16 UTC, misut requested changes

2022-07-08 04:16 UTC, misut commented on baek/1260.py
> +relation = [[] for _ in range(N+1)]
praise: 오 그래프 linked list로 구현하는 거 어케 알았음? 좀 하네

2022-07-08 04:16 UTC, misut commented on baek/1149.py
> +print(min(cost[N-1]))
question(blocking): 이거 저번주 문제 아님? 왜 들어갔음

2022-07-08 16:11 UTC, tunkcalb commented on baek/1149.py
> +print(min(cost[N-1]))
이거 데스크탑에만 있었던 거 저장되고 어째 하면서 같이 올라감;;

2022-07-09 14:51 UTC, misut commented on baek/1149.py
> +print(min(cost[N-1]))
ㅋㅋㅋㅋㅋㅋ 아직도 컨플릭트 해결 못했네... [링크](https://backlog.com/git-tutorial/kr/stepup/stepup2_7.html) 확인해봐라

2022-07-13 09:41 UTC, merged